#!/bin/bash

PHP="php7.4"

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Install vim
sudo apt install vim

# Install zsh
echo 'Install zsh and zplug'
echo '-----------------'
sudo apt install gawk zsh
rm -rf $HOME/.zsh
curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
chsh -s $(which zsh)

# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

# Global configs for GIT
git config --global core.editor "vim"
git config --global user.name "Jyrki De Neve"
git config --global user.email "jyrki.deneve@gmail.com"

# Install starship.rs
curl -fsSL https://starship.rs/install.sh | bash

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/starship.toml $HOME/.config/starship.toml

# Symlink profile
rm $HOME/.profile
ln -s $HOME/.dotfiles/shell/.profile $HOME/.profile

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
rm $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

echo 'Install bat'
echo '-----------'
sudo apt install bat

echo 'Install nvm'
echo '-----------'
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
nvm install 14
mkdir ~/.npm-global
npm config set prefix '~/.npm-global'
npm completion >> ~/.zshrc

echo 'Install php'
echo '-----------'
sudo add-apt-repository ppa:ondrej/php
sudo apt update
sudo apt install $PHP

echo 'Install composer'
echo '----------------'
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
sudo mv composer.phar /usr/local/bin/composer

echo 'Install PECL'
echo '------------'
sudo apt install php-pear
sudo apt install php-dev

echo 'Install imagick'
echo '---------------'
sudo apt install imagemagick
sudo apt install libmagickwand-dev
sudo pecl install imagick

echo 'Install memcached'
echo '-----------------'
sudo apt install libmemcached-dev
sudo pecl install memcached

echo 'Install laravel valet'
echo '---------------------'
sudo apt install network-manager libnss3-tools jq xsel
sudo apt install php7.4-cli php7.4-fpm php7.4-curl php7.4-mbstring php7.4-mysql php7.4-xml php7.4-zip php7.4-mbstring
sudo apt install php8.0-cli php8.0-fpm php8.0-curl php8.0-mbstring php8.0-mysql php8.0-xml php8.0-zip php8.0-mbstring
composer global require cpriego/valet-linux
composer global require tightenco/takeout
composer global require squizlabs/php_codesniffer
valet install
mkdir $HOME/web
cd $HOME/web
valet park
cd $HOME

echo 'Manually install'
echo '----------------'
cd $HOME/Downloads
wget https://github.com/tonsky/FiraCode/releases/download/5.2/Fira_Code_v5.2.zip
unzip Fira_Code_v5.2.zip -d fira_code
mkdir $HOME/.local/share/fonts
mv fira_code $HOME/.local/share/fonts/.
rm Fira_Code_v5.2.zip

echo 'Reboot your system!'
