#!/bin/bash

PHP="php7.3"

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Install zsh
echo 'Install zsh and zplug'
echo '-----------------'
apt install gawk
rm -rf $HOME/.zsh
curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
chsh -s $(which zsh)

# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludesfile $HOME/.global-gitignore

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink profile
rm $HOME/.profile
ln -s $HOME/.dotfiles/shell/.profile $HOME/.profile

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
rm $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

echo 'Install bat'
echo '-----------'
wget https://github.com/sharkdp/bat/releases/download/v0.12.1/bat_0.12.1_amd64.deb
dpkg -i bat_0.12.1_amd64.deb

echo 'Install z'
echo '---------'
mkdir $HOME/apps
cd $HOME/apps
git clone https://github.com/rupa/z.git
cd $HOME

echo 'Install node'
echo '-----------'
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs

echo 'Install php'
echo '-----------'
add-apt-repository ppa:ondrej/php
apt-update
apt-get install $PHP

echo 'Install composer'
echo '----------------'
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
mv composer.phar /usr/local/bin/composer

echo 'Install PECL'
echo '------------'
apt install php-pear
apt install php-dev

echo 'Install imagick'
echo '---------------'
apt install imagemagick
apt install libmagickwand-dev
pecl install imagick

echo 'Install memcached'
echo '-----------------'
apt install libmemcached-dev
pecl install memcached

echo 'Install xdebug'
echo '--------------'
pecl install xdebug

echo 'Install redis'
echo '-------------'
pecl install redis

echo 'Install laravel valet'
echo '---------------------'
apt install network-manager libnss3-tools jq xsel libmcrypt-dev
apt install $PHP-cli $PHP-curl $PHP-mbstring $PHP-mcrypt $PHP-xml $PHP-zip $PHP-mbstring
pecl install mcrypt
composer global require cpriego/valet-linux
valet install
systemctl disable systemd-resolved.service

echo 'Install mysql'
echo '-------------'
apt install mysql-server $PHP-mysql
mysql_secure_installation
mysqladmin -u root password

echo 'Reboot your system!'